// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	GetRequest
	GetResponse
*/
package app

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetResponse struct {
	Country string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "app.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "app.GetResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0x28, 0x50, 0xe2,
	0xe1, 0xe2, 0x72, 0x4f, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x52, 0xe7, 0xe2,
	0x06, 0xf3, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0x4b, 0xf3,
	0x4a, 0x8a, 0x2a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x23, 0x7d, 0x2e, 0x66,
	0xf7, 0xd4, 0x7c, 0x21, 0x0d, 0x10, 0x55, 0x22, 0xc4, 0xaf, 0x97, 0x58, 0x50, 0xa0, 0x87, 0x30,
	0x47, 0x4a, 0x00, 0x21, 0x00, 0x31, 0xca, 0x89, 0x35, 0x0a, 0x64, 0x5d, 0x12, 0x1b, 0xd8, 0x6a,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x21, 0xc8, 0xc1, 0x8b, 0x00, 0x00, 0x00,
}
